name: Reusable WF
 
on:
  workflow_call:
    inputs:
      build_dir:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Print folder
        run: ls -lrtha
